# Generated by Django 3.1 on 2020-08-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_comp',
            field=models.BooleanField(default=False),
        ),
    ]
