# Generated by Django 3.1 on 2020-08-09 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_comp',
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('IFSC', models.CharField(blank=True, max_length=10)),
                ('acc_no', models.CharField(blank=True, max_length=40)),
                ('acc_type', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
