# Generated by Django 3.1 on 2020-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200809_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
