# Generated by Django 3.1 on 2020-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200817_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='acc_no',
            new_name='acccount_number',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='acc_type',
        ),
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.BooleanField(choices=[('current', 'current'), ('saving', 'saving')], default=False),
        ),
    ]
