# Generated by Django 3.1 on 2020-08-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200818_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='IFSC',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='acccount_number',
        ),
        migrations.AddField(
            model_name='bank',
            name='IFSC_code',
            field=models.CharField(blank=True, default='IFSC code', max_length=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='account_number',
            field=models.CharField(default='ACCOUNT NUMBER', max_length=40),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_holder_name',
            field=models.CharField(default='YOUR NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('current', 'current'), ('saving', 'saving')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, default='BANK NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, default='BRANCH', max_length=100),
        ),
    ]
