# Generated by Django 3.1 on 2020-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200818_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='IFSC_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('current', 'current'), ('saving', 'saving')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
