# Generated by Django 3.1 on 2020-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200820_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='i_am',
            field=models.CharField(blank=True, choices=[('agent', 'agnet'), ("vihav's client", "vihav's client")], max_length=40),
        ),
    ]
