# Generated by Django 3.1 on 2020-08-20 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_i_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
