# Generated by Django 3.1 on 2020-08-20 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_bank_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
