# Generated by Django 3.1 on 2020-08-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='i_am',
            field=models.CharField(blank=True, choices=[("Vihav's client", "Vihav's client"), ("Vihav's employee", "Vihav's employee"), ('Vendor or Suppliers', 'Vendor or Supplier'), ('Channel partner', 'Channel partner'), ('Channel partner', 'Channel partner'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
