# Generated by Django 3.1 on 2020-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200825_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.CharField(blank=True, choices=[('KEYSTONE SKYVILLAS', 'KEYSTONE SKYVILLAS'), ('WEALTH SQUARE', 'WEALTH SQUARE'), ('VIHAV BUSINESS SQUARE', 'VIHAV BUSINESS SQUARE'), ('VIHAV SUPREMUS', 'VIHAV SUPREMUS'), ('VIHAV SKYONE', 'VIHAV SKYONE'), ('VIHAV TRADE CENTRE', 'VIHAV TRADE CENTRE'), ('VIHAV KEYSTONE MANSIONS', 'VIHAV KEYSTONE MANSIONS'), ('VIHAV KEYSTONE MANSIONS-2', 'VIHAV KEYSTONE MANSIONS-2'), ('VIHAV ELITE SQUARE', 'VIHAV ELITE SQUARE'), ('VIAHV EXCELUS', 'VIAHV EXCELUS'), ('VIHAV ENSIGN', 'VIHAV ENSIGN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='i_am',
            field=models.CharField(blank=True, choices=[("Vihav's client", "Vihav's client"), ("Vihav's employee", "Vihav's employee"), ('Vendor or Suppliers', 'Vendor or Supplier'), ('Channel partner', 'Channel partner'), ('Other', 'Other')], max_length=40),
        ),
    ]
