# Generated by Django 3.1 on 2020-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200909_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Saving', 'Saving'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
