# Generated by Django 3.1 on 2020-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200910_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
