# Generated by Django 3.1 on 2020-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20200814_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='alert',
            field=models.CharField(blank=True, choices=[('success', 'green (approved)'), ('warning', 'yellow (pending)'), ('danger', 'red (canceled)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
