# Generated by Django 3.1 on 2020-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20200817_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='referrals',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('fail', 'fail')], default='pending', max_length=30),
        ),
    ]
