# Generated by Django 3.1 on 2020-08-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20200820_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrals',
            old_name='number',
            new_name='contact_number',
        ),
    ]
