# Generated by Django 3.1 on 2020-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0009_auto_20200820_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='alert',
            field=models.CharField(blank=True, choices=[('table-success', 'green (approved)'), ('table-warning', 'yellow (pending)'), ('table-danger', 'red (canceled)')], default='table-warning', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='note',
            field=models.TextField(blank=True, default='---', max_length=350),
        ),
    ]
