# Generated by Django 3.1 on 2020-08-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_auto_20200820_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referrals',
            old_name='location',
            new_name='city',
        ),
    ]
