# Generated by Django 3.1 on 2020-08-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0011_auto_20200821_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('not reviewed', 'not reviewed'), ('pending', 'pending'), ('fail', 'fail')], default='not reviewed', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='note',
            field=models.TextField(blank=True, default='---', max_length=150),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('not reviewed', 'not reviewed'), ('pending', 'pending'), ('fail', 'fail')], default='not reviewed', max_length=30),
        ),
    ]
