# Generated by Django 3.1 on 2020-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0012_auto_20200824_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='note',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
