# Generated by Django 3.1 on 2020-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0013_auto_20200824_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
