# Generated by Django 3.1 on 2020-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0014_referrals_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='site',
            field=models.CharField(blank=True, choices=[('KEYSTONE SKYVILLAS', 'KEYSTONE SKYVILLAS'), ('WEALTH SQUARE', 'WEALTH SQUARE'), ('VIHAV BUSINESS SQUARE', 'VIHAV BUSINESS SQUARE'), ('VIHAV SUPREMUS', 'VIHAV SUPREMUS'), ('VIHAV SKYONE', 'VIHAV SKYONE'), ('VIHAV TRADE CENTRE', 'VIHAV TRADE CENTRE'), ('VIHAV KEYSTONE MANSIONS', 'VIHAV KEYSTONE MANSIONS'), ('VIHAV KEYSTONE MANSIONS-2', 'VIHAV KEYSTONE MANSIONS-2'), ('VIHAV ELITE SQUARE', 'VIHAV ELITE SQUARE'), ('VIAHV EXCELUS', 'VIAHV EXCELUS'), ('VIHAV ENSIGN', 'VIHAV ENSIGN'), ('Not Sure ', 'Not Sure')], max_length=30),
        ),
    ]
